version: '3.7'
services:
  mongodb_container:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: testuser
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: nestjs-mongo-sample
    ports:
      - 27017:27017
  rabbitmq:
    image: rabbitmq
    ports:
      - '5672:5672'